### PR TITLE
[WIP] first attempt at Python package

### PR DESCRIPTION
**Pull request by talumbau**
- adds Travis CI
- setup.py for installation
- tests with py.test
- uses recent TESTED_DONT_TOUCH code

### CODE REVIEW

**Comment by talumbau** [comment]
This is a work in progress. Things left to be done:

- [ ] merge in latest changes
- [ ] verify that latest version of TESTED_DONT_TOUCH produces same results as this package
- [ ] make Travis CI work

**Comment by evan-magnusson** [comment]
@talumbau How did you get those check boxes in your comment?

**Comment by talumbau** [comment]
@evan-magnusson Github understands a special syntax that happens to very handy:

https://help.github.com/articles/writing-on-github/

**Comment by rickecon** [comment]
@talumbau, @evan-magnusson and I will go over this tomorrow morning.

**Comment by talumbau** [comment]
OK @rickecon, but don't get into the guts too much. The main contributions are:

- use a function `run_....` inside of SS.py and TPI.py so that we don't have to use subprocess to call that work

- try to avoid using pickle files to pass data between SS and TPI (mostly successful, still some work to do)

- abstract certain read-only parameters to a parameters.py file

The goal is to get this in to a reasonable shape so that further changes to TESTED_DONT_TOUCH can happen inside this package.

**Pull request merged**
