### PR TITLE
clean out unused tp functions

### PR DESCRIPTION
**Pull request by jdebacker**
This pull request:
- Deletes alternative, unused versions of get_Ympath, get_Kmpath, get_Lmpath
- Deletes convergence method
- Renames TPI function as TP- it is called after fsolve to get all the other endogenous variables along the time path (TPI_fsolve just returns rpath, wpath).  We might want to consolidate this later - some redundancy between TP and TPI_fsolve.

### CODE REVIEW

**Comment by jdebacker** [comment]
Second commit to the pull request updates names of numpy arrays of variables from things like "epsvec" to things like "epsilon".

**Comment by rickecon** [comment]
The nice thing about epsvec instead of epsilon is that the name communicates the idea that the object is a vector of epsilons. This is more intuitive as we add more industries and those vectors become longer.

**Comment by rickecon** [comment]
And we are correctly removing the bisection method, referred to above, from this code. The bisection method does not reliably work with more than one variable (see Kopecki, http://www.karenkopecky.net/Teaching/eco613614/Notes_RootFindingMethods.pdf).

**Comment by jdebacker** [comment]
Re names of arrays of variables.  My thought is that the "vec" suffix is redundant.  Because we are going to write the code such that it is generalizable to SxJxMxIxT, everything will be done with array operations and so it is implied that the length along any dimension may be greater than one.

**Comment by rickecon** [comment]
I agree @jdebacker.

**Pull request merged**
