### PR TITLE
Step 1 of Jason's doc

### PR DESCRIPTION
**Pull request by isaacswift**
I did some debugging of the code.  The code is running, but it doesn't converge.  @jdebacker  let me know if this looks like the right idea.  @evan-magnusson if you could help with debugging.

### CODE REVIEW

**Comment by jdebacker** [comment]
This is what I was thinking.  I'm not seeing anything that would suggest it wouldn't converge.  Should we try saving the errors and guesses (r, w, TH, factor) and plotting?  Maybe we can trace out the excess demand functions and find some information there (e.g. local min or very flat functions)?

**Comment by jdebacker** [comment]
One idea - the model hasn't changed, just the solution.   What do the
excess demands look like with the "old" equilibrium values of r, w, TH,
factor?

**Comment by jdebacker** [comment]
Another idea - set delta = 0 and see how it works. This is the part I'm
most unsure about.

**Comment by evan-magnusson** [comment]
Setting delta = 0 doesn't change anything too much.  It still doesn't converge.

**Comment by jdebacker** [comment]
Hmm, not sure.  With delta = 0, then C=Y (the capital stock is unchanged each period).  And we should be able to use HH demand for C (which we can find given r,w,TH,factor) to find demand for K and L from the firm FOCs (using the guesses at r and w).  

It would seem there is a fixed point in here where the factor demands equal factor supplies.  I can imagine that it's hard to find, but I can't see what it wouldn't exist.  

Back to the plotting suggestion - it can be useful just to see if the excess demand are monotonic in r, w, TH, factor.  I'd guess that excess demand for capital is monotonic in r and excess demand for labor is monotonic in w, but it's less clear how the other eq'm variables affect these.  It's also not clear how w affects excess demand in the capital market.  All this is to say that the eq'm might be tough to find.

Fullerton and Rogers (1993) describe finding the eq'm in this way.  Their book not very recent, but they mention this paper https://ecompapers.biz.uwa.edu.au/paper/PDF%20of%20Discussion%20Papers/1982/82-05.pdf  However, after scanning the paper, I didn't see anything especially relevant for this issue.  They also mention the "Scarf's grid search algorithm" and and dissertation chapter by an O. Merrill that I couldn't find as two alternative algorithms.  I don't know anything about these.

**Comment by jdebacker** [comment]
Anything weird going on with the stationarization?  Do we need to change
everything to move from using the firm FOCs from getting prices to getting
quantities?

**Pull request merged**
